import operator
from datetime import datetime
from pathlib import Path
from typing import Annotated, Literal

from dotenv import load_dotenv
from langchain_core.messages import (
    AIMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import InjectedToolCallId, tool
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph, add_messages
from langgraph.prebuilt import ToolNode
from langgraph.types import Command
from pydantic import BaseModel

from ai_launchpad.langgraph_module.multi_agent.supervisor.copywriter import (
    graph as copywriter_agent,
)
from ai_launchpad.langgraph_module.multi_agent.supervisor.researcher import (
    graph as research_agent,
)


load_dotenv()


# Resolve the prompt path relative to supervisor.py.
# This allows the application to run from any terminal directory.
CURRENT_DIR = Path(__file__).resolve().parent
SUPERVISOR_PROMPT_PATH = CURRENT_DIR / "prompts" / "supervisor.md"

with SUPERVISOR_PROMPT_PATH.open(
    "r",
    encoding="utf-8",
) as prompt_file:
    supervisor_prompt = prompt_file.read()


class SupervisorState(BaseModel):
    """
    State shared by the supervisor and its sub-agents.

    messages:
        Stores the conversation and agent messages.

    research_reports:
        Stores reports generated by the researcher so they can be
        passed to the copywriter.

    task_description:
        Stores the specific task that the supervisor assigns to a
        researcher or copywriter.
    """

    messages: Annotated[list, add_messages] = []
    research_reports: Annotated[list, operator.add] = []
    task_description: str | None = None


@tool
async def handoff_to_subagent(
    agent_name: Literal["researcher", "copywriter"],
    task_description: str,
    tool_call_id: Annotated[str, InjectedToolCallId],
):
    """
    Assign a task to either the researcher or copywriter agent.

    Args:
        agent_name:
            Name of the sub-agent. Must be researcher or copywriter.

        task_description:
            A focused description of the task assigned to the sub-agent.

        tool_call_id:
            ID of the current tool call, injected automatically by
            LangGraph.

    Returns:
        A Command that updates the graph state and routes execution to
        the selected sub-agent.
    """

    update = {
        "task_description": task_description,
        "messages": [
            ToolMessage(
                name=f"handoff_to_{agent_name}",
                content=(
                    f"Successfully handed off task to "
                    f"{agent_name}."
                ),
                tool_call_id=tool_call_id,
            )
        ],
    }

    return Command(
        goto=f"call_{agent_name}",
        update=update,
    )


async def call_researcher(
    state: SupervisorState,
    config: RunnableConfig,
):
    """
    Invoke the researcher subgraph.

    Only the assigned task is passed to the researcher. This keeps the
    researcher's context focused and avoids sending the supervisor's
    complete conversation history.
    """

    if not state.task_description:
        return {
            "messages": [
                AIMessage(
                    name="researcher",
                    content="No research task was provided.",
                )
            ]
        }

    research_response = await research_agent.ainvoke(
        input={
            "messages": [
                HumanMessage(
                    content=state.task_description
                )
            ],
        },
        config=config,
    )

    researcher_messages = research_response.get(
        "messages",
        [],
    )

    researcher_content = (
        researcher_messages[-1].content
        if researcher_messages
        else "The researcher completed without returning a message."
    )

    ai_message = AIMessage(
        name="researcher",
        content=researcher_content,
    )

    return {
        "research_reports": research_response.get(
            "research_reports",
            [],
        ),
        "messages": [ai_message],
    }


async def call_copywriter(
    state: SupervisorState,
    config: RunnableConfig,
):
    """
    Invoke the copywriter subgraph.

    The copywriter receives the assigned task and all research reports
    currently stored in the supervisor state.
    """

    if not state.task_description:
        return {
            "messages": [
                AIMessage(
                    name="copywriter",
                    content="No writing task was provided.",
                )
            ]
        }

    copywriter_response = await copywriter_agent.ainvoke(
        input={
            "messages": [
                HumanMessage(
                    content=state.task_description
                )
            ],
            "research_reports": state.research_reports,
        },
        config=config,
    )

    copywriter_messages = copywriter_response.get(
        "messages",
        [],
    )

    copywriter_content = (
        copywriter_messages[-1].content
        if copywriter_messages
        else "The copywriter completed without returning a message."
    )

    ai_message = AIMessage(
        name="copywriter",
        content=copywriter_content,
    )

    return {
        "messages": [ai_message]
    }


llm = ChatOpenAI(
    name="Supervisor",
    model="gpt-5-mini-2025-08-07",
    reasoning_effort="low",
)


tools = [
    handoff_to_subagent,
]


# parallel_tool_calls=False ensures the supervisor hands off one task
# at a time instead of triggering multiple sub-agent handoffs together.
llm_with_tools = llm.bind_tools(
    tools,
    parallel_tool_calls=False,
)


async def supervisor(
    state: SupervisorState,
):
    """Run the main supervisor agent."""

    system_message = SystemMessage(
        content=supervisor_prompt.format(
            current_datetime=datetime.now()
        )
    )

    response = await llm_with_tools.ainvoke(
        [system_message] + state.messages
    )

    return {
        "messages": [response]
    }


async def supervisor_router(
    state: SupervisorState,
) -> str:
    """
    Route to the tools node when the supervisor makes a tool call.

    If no tool call is made, the workflow ends and the supervisor's
    response becomes the final response.
    """

    latest_message = state.messages[-1]

    if latest_message.tool_calls:
        return "tools"

    return END


builder = StateGraph(SupervisorState)


builder.add_node(
    "supervisor",
    supervisor,
)

builder.add_node(
    "tools",
    ToolNode(tools),
)

builder.add_node(
    "call_researcher",
    call_researcher,
)

builder.add_node(
    "call_copywriter",
    call_copywriter,
)


builder.set_entry_point(
    "supervisor"
)


builder.add_conditional_edges(
    "supervisor",
    supervisor_router,
    {
        "tools": "tools",
        END: END,
    },
)


# The handoff_to_subagent tool uses Command(goto=...) to route from
# the tools node directly to the selected sub-agent. Therefore, a
# normal tools-to-supervisor edge is not required.


# After a sub-agent finishes, execution returns to the supervisor.
builder.add_edge(
    "call_researcher",
    "supervisor",
)

builder.add_edge(
    "call_copywriter",
    "supervisor",
)


graph = builder.compile(
    checkpointer=MemorySaver()
)


# Optional graph visualization:
#
# from IPython.display import Image, display
#
# graph_image = Image(
#     graph.get_graph(
#         xray=True
#     ).draw_mermaid_png()
# )
#
# display(graph_image)